CRITICAL - 2021-06-08 15:54:24 --> Call to undefined function CodeIgniter\locale_set_default()
#0 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\bootstrap.php(157): CodeIgniter\CodeIgniter->initialize()
#1 C:\Users\Ace\Desktop\krefa\spark(45): require('C:\\Users\\Ace\\De...')
#2 {main}
CRITICAL - 2021-06-08 15:57:12 --> Call to undefined function CodeIgniter\locale_set_default()
#0 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\bootstrap.php(157): CodeIgniter\CodeIgniter->initialize()
#1 C:\Users\Ace\Desktop\krefa\spark(45): require('C:\\Users\\Ace\\De...')
#2 {main}
CRITICAL - 2021-06-08 15:57:18 --> Call to undefined function CodeIgniter\locale_set_default()
#0 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\bootstrap.php(157): CodeIgniter\CodeIgniter->initialize()
#1 C:\Users\Ace\Desktop\krefa\spark(45): require('C:\\Users\\Ace\\De...')
#2 {main}
CRITICAL - 2021-06-08 15:57:19 --> Call to undefined function CodeIgniter\locale_set_default()
#0 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\bootstrap.php(157): CodeIgniter\CodeIgniter->initialize()
#1 C:\Users\Ace\Desktop\krefa\spark(45): require('C:\\Users\\Ace\\De...')
#2 {main}
CRITICAL - 2021-06-08 16:00:23 --> Call to undefined function CodeIgniter\locale_set_default()
#0 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\bootstrap.php(157): CodeIgniter\CodeIgniter->initialize()
#1 C:\Users\Ace\Desktop\krefa\spark(45): require('C:\\Users\\Ace\\De...')
#2 {main}
CRITICAL - 2021-06-08 16:01:42 --> Call to undefined function CodeIgniter\locale_set_default()
#0 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\bootstrap.php(157): CodeIgniter\CodeIgniter->initialize()
#1 C:\Users\Ace\Desktop\krefa\spark(45): require('C:\\Users\\Ace\\De...')
#2 {main}
ERROR - 2021-06-08 09:06:28 --> Error connecting to the database: No connection could be made because the target machine actively refused it
CRITICAL - 2021-06-08 09:06:28 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
#0 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Model.php(197): CodeIgniter\Database\BaseBuilder->get()
#3 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\Users\Ace\Desktop\krefa\app\Controllers\EventsApi.php(19): CodeIgniter\BaseModel->findAll()
#5 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\EventsApi->index()
#6 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EventsApi))
#7 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Users\Ace\Desktop\krefa\public\index.php(36): CodeIgniter\CodeIgniter->run()
#9 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\Users\\Ace\\De...')
#10 {main}
ERROR - 2021-06-08 09:06:36 --> Error connecting to the database: Unknown database 'ci4'
CRITICAL - 2021-06-08 09:06:36 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'ci4'
#0 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Model.php(197): CodeIgniter\Database\BaseBuilder->get()
#3 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\Users\Ace\Desktop\krefa\app\Controllers\EventsApi.php(19): CodeIgniter\BaseModel->findAll()
#5 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\EventsApi->index()
#6 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EventsApi))
#7 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Users\Ace\Desktop\krefa\public\index.php(36): CodeIgniter\CodeIgniter->run()
#9 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\Users\\Ace\\De...')
#10 {main}
ERROR - 2021-06-08 09:07:00 --> Error connecting to the database: Unknown database 'ci4'
ERROR - 2021-06-08 09:07:36 --> Error connecting to the database: Unknown database 'ci4'
ERROR - 2021-06-08 09:07:36 --> Error connecting to the database: Unknown database 'ci4'
ERROR - 2021-06-08 09:09:11 --> Error connecting to the database: No connection could be made because the target machine actively refused it
CRITICAL - 2021-06-08 09:09:11 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
#0 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1881): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Model.php(197): CodeIgniter\Database\BaseBuilder->get()
#3 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\BaseModel.php(603): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\Users\Ace\Desktop\krefa\app\Controllers\EventsApi.php(19): CodeIgniter\BaseModel->findAll()
#5 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\EventsApi->index()
#6 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\EventsApi))
#7 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Users\Ace\Desktop\krefa\public\index.php(36): CodeIgniter\CodeIgniter->run()
#9 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\Users\\Ace\\De...')
#10 {main}
ERROR - 2021-06-08 12:41:01 --> Error connecting to the database: No connection could be made because the target machine actively refused it
ERROR - 2021-06-08 12:41:03 --> Error connecting to the database: No connection could be made because the target machine actively refused it
CRITICAL - 2021-06-08 13:16:12 --> reequired is not a valid rule.
#0 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Validation\Validation.php(321): CodeIgniter\Validation\Exceptions\ValidationException::forRuleNotFound('reequired')
#1 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Validation\Validation.php(159): CodeIgniter\Validation\Validation->processRules('tempat', 'tempat', NULL, Array, Array)
#2 C:\Users\Ace\Desktop\krefa\app\Controllers\PeopleApi.php(26): CodeIgniter\Validation\Validation->run(Array, 'insertEvent')
#3 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\PeopleApi->create()
#4 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PeopleApi))
#5 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\Ace\Desktop\krefa\public\index.php(36): CodeIgniter\CodeIgniter->run()
#7 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\Users\\Ace\\De...')
#8 {main}
CRITICAL - 2021-06-08 13:17:31 --> insertPeople is not a validation rules group.
#0 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Validation\Validation.php(601): CodeIgniter\Validation\Exceptions\ValidationException::forGroupNotFound('insertPeople')
#1 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Validation\Validation.php(119): CodeIgniter\Validation\Validation->loadRuleGroup('insertPeople')
#2 C:\Users\Ace\Desktop\krefa\app\Controllers\PeopleApi.php(26): CodeIgniter\Validation\Validation->run(Array, 'insertPeople')
#3 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\PeopleApi->create()
#4 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PeopleApi))
#5 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\Ace\Desktop\krefa\public\index.php(36): CodeIgniter\CodeIgniter->run()
#7 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\Users\\Ace\\De...')
#8 {main}
CRITICAL - 2021-06-08 13:19:33 --> There is no data to insert.
#0 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, true)
#2 C:\Users\Ace\Desktop\krefa\app\Controllers\PeopleApi.php(33): CodeIgniter\Model->insert(Array)
#3 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\PeopleApi->create()
#4 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PeopleApi))
#5 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\Ace\Desktop\krefa\public\index.php(36): CodeIgniter\CodeIgniter->run()
#7 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\Users\\Ace\\De...')
#8 {main}
CRITICAL - 2021-06-08 13:20:54 --> syntax error, unexpected token "public", expecting "]"
#0 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(282): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\Users\\Ace\\De...')
#1 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(247): CodeIgniter\Autoloader\Autoloader->loadInNamespace('Config\\Validati...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('Config\\Validati...')
#3 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Config\Factories.php(149): class_exists('Config\\Validati...')
#4 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Config\Factories.php(115): CodeIgniter\Config\Factories::locateClass(Array, 'Validation')
#5 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Common.php(228): CodeIgniter\Config\Factories::__callStatic('config', Array)
#6 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Config\Services.php(841): config('Validation')
#7 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Config\BaseService.php(263): CodeIgniter\Config\Services::validation(NULL, false)
#8 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Config\BaseService.php(192): CodeIgniter\Config\BaseService::__callStatic('validation', Array)
#9 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Config\Services.php(838): CodeIgniter\Config\BaseService::getSharedInstance('validation', NULL)
#10 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Config\BaseService.php(263): CodeIgniter\Config\Services::validation()
#11 C:\Users\Ace\Desktop\krefa\app\Controllers\PeopleApi.php(15): CodeIgniter\Config\BaseService::__callStatic('validation', Array)
#12 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(903): App\Controllers\PeopleApi->__construct()
#13 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(429): CodeIgniter\CodeIgniter->createController()
#14 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\Users\Ace\Desktop\krefa\public\index.php(36): CodeIgniter\CodeIgniter->run()
#16 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\Users\\Ace\\De...')
#17 {main}
ERROR - 2021-06-08 13:21:39 --> Unknown column 'nama' in 'field list'
CRITICAL - 2021-06-08 13:21:39 --> Unknown column 'nama' in 'field list'
#0 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `pe...')
#1 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pe...')
#2 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pe...')
#3 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pe...', Array, false)
#4 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\Users\Ace\Desktop\krefa\app\Controllers\PeopleApi.php(33): CodeIgniter\Model->insert(Array)
#8 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\PeopleApi->create()
#9 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PeopleApi))
#10 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\Ace\Desktop\krefa\public\index.php(36): CodeIgniter\CodeIgniter->run()
#12 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\Users\\Ace\\De...')
#13 {main}
ERROR - 2021-06-08 13:23:03 --> Unknown column 'nama' in 'field list'
CRITICAL - 2021-06-08 13:23:03 --> Unknown column 'nama' in 'field list'
#0 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `pe...')
#1 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pe...')
#2 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pe...')
#3 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pe...', Array, false)
#4 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\Users\Ace\Desktop\krefa\app\Controllers\PeopleApi.php(33): CodeIgniter\Model->insert(Array)
#8 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\PeopleApi->create()
#9 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PeopleApi))
#10 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\Ace\Desktop\krefa\public\index.php(36): CodeIgniter\CodeIgniter->run()
#12 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\Users\\Ace\\De...')
#13 {main}
ERROR - 2021-06-08 13:24:58 --> Unknown column 'nama' in 'field list'
CRITICAL - 2021-06-08 13:24:58 --> Unknown column 'nama' in 'field list'
#0 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `pe...')
#1 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pe...')
#2 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pe...')
#3 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pe...', Array, false)
#4 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\Users\Ace\Desktop\krefa\app\Controllers\PeopleApi.php(33): CodeIgniter\Model->insert(Array)
#8 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\PeopleApi->create()
#9 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PeopleApi))
#10 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\Ace\Desktop\krefa\public\index.php(36): CodeIgniter\CodeIgniter->run()
#12 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\Users\\Ace\\De...')
#13 {main}
ERROR - 2021-06-08 13:25:01 --> Unknown column 'nama' in 'field list'
CRITICAL - 2021-06-08 13:25:01 --> Unknown column 'nama' in 'field list'
#0 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('INSERT INTO `pe...')
#1 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pe...')
#2 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pe...')
#3 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2277): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pe...', Array, false)
#4 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Model.php(259): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\BaseModel.php(774): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\Users\Ace\Desktop\krefa\app\Controllers\PeopleApi.php(33): CodeIgniter\Model->insert(Array)
#8 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\PeopleApi->create()
#9 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PeopleApi))
#10 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\Ace\Desktop\krefa\public\index.php(36): CodeIgniter\CodeIgniter->run()
#12 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\Users\\Ace\\De...')
#13 {main}
ERROR - 2021-06-08 13:27:58 --> Error connecting to the database: Class "SQLite3" not found
ERROR - 2021-06-08 13:28:29 --> Error connecting to the database: Class "SQLite3" not found
ERROR - 2021-06-08 13:29:01 --> Error connecting to the database: Class "SQLite3" not found
ERROR - 2021-06-08 13:29:42 --> No database selected
ERROR - 2021-06-08 13:29:42 --> No database selected
ERROR - 2021-06-08 13:31:32 --> Error connecting to the database: Unknown database 'ci4'
ERROR - 2021-06-08 13:31:32 --> Error connecting to the database: Unknown database 'ci4'
ERROR - 2021-06-08 13:32:21 --> Error connecting to the database: Unknown database 'ci4'
ERROR - 2021-06-08 13:32:21 --> Error connecting to the database: Unknown database 'ci4'
ERROR - 2021-06-08 13:32:45 --> Error connecting to the database: Unknown database 'ci4'
ERROR - 2021-06-08 13:32:45 --> Error connecting to the database: Unknown database 'ci4'
ERROR - 2021-06-08 13:34:07 --> Error connecting to the database: Unknown database 'ci4'
ERROR - 2021-06-08 13:34:07 --> Error connecting to the database: Unknown database 'ci4'
ERROR - 2021-06-08 13:36:43 --> Error connecting to the database: Unknown database 'ci4'
ERROR - 2021-06-08 13:37:30 --> Error connecting to the database: Unknown database 'ci4'
ERROR - 2021-06-08 13:38:03 --> Error connecting to the database: Unknown database 'ci4'
ERROR - 2021-06-08 13:38:41 --> Error connecting to the database: Unknown database 'ci4'
ERROR - 2021-06-08 13:38:51 --> Error connecting to the database: Unknown database 'ci4'
ERROR - 2021-06-08 13:40:09 --> Can't create database 'ci4'; database exists
ERROR - 2021-06-08 17:36:41 --> Error connecting to the database: No connection could be made because the target machine actively refused it
ERROR - 2021-06-08 17:36:43 --> Error connecting to the database: No connection could be made because the target machine actively refused it
ERROR - 2021-06-08 17:37:47 --> Error connecting to the database: Class "SQLite3" not found
ERROR - 2021-06-08 17:38:05 --> Error connecting to the database: Class "SQLite3" not found
ERROR - 2021-06-08 17:43:49 --> No database selected
ERROR - 2021-06-08 17:43:50 --> No database selected
ERROR - 2021-06-08 17:44:12 --> Error connecting to the database: Unknown database 'ci4'
ERROR - 2021-06-08 17:44:12 --> Error connecting to the database: Unknown database 'ci4'
ERROR - 2021-06-08 17:44:13 --> Error connecting to the database: Unknown database 'ci4'
ERROR - 2021-06-08 17:44:13 --> Error connecting to the database: Unknown database 'ci4'
ERROR - 2021-06-08 17:44:41 --> Error connecting to the database: Unknown database 'ci4'
ERROR - 2021-06-08 17:44:53 --> Error connecting to the database: Unknown database 'ci4'
ERROR - 2021-06-08 17:45:07 --> Error connecting to the database: Unknown database 'ci4'
ERROR - 2021-06-08 17:52:29 --> Error connecting to the database: Unknown database 'ci4'
ERROR - 2021-06-08 17:53:48 --> Error connecting to the database: Unknown database 'ci4'
ERROR - 2021-06-08 18:01:15 --> Error connecting to the database: Unknown database 'ci4'
ERROR - 2021-06-08 18:02:06 --> Error connecting to the database: Unknown database 'ci4'
ERROR - 2021-06-08 18:03:05 --> Error connecting to the database: Unknown database 'ci4'
ERROR - 2021-06-08 18:05:12 --> Error connecting to the database: Unknown database 'ci4'
CRITICAL - 2021-06-08 18:59:16 --> syntax error, unexpected token ";"
#0 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(282): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\Users\\Ace\\De...')
#1 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(247): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(888): class_exists('\\App\\Controller...', true)
#4 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(424): CodeIgniter\CodeIgniter->startController()
#5 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\Ace\Desktop\krefa\public\index.php(36): CodeIgniter\CodeIgniter->run()
#7 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\Users\\Ace\\De...')
#8 {main}
CRITICAL - 2021-06-08 19:02:55 --> max_lenght is not a valid rule.
#0 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Validation\Validation.php(321): CodeIgniter\Validation\Exceptions\ValidationException::forRuleNotFound('max_lenght')
#1 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Validation\Validation.php(159): CodeIgniter\Validation\Validation->processRules('whatsapp', 'whatsapp', '416964918461923...', Array, Array)
#2 C:\Users\Ace\Desktop\krefa\app\Controllers\PeopleApi.php(32): CodeIgniter\Validation\Validation->run(Array, 'insertPeople')
#3 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\PeopleApi->create()
#4 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PeopleApi))
#5 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\Ace\Desktop\krefa\public\index.php(36): CodeIgniter\CodeIgniter->run()
#7 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\Users\\Ace\\De...')
#8 {main}
CRITICAL - 2021-06-08 19:07:44 --> There is no data to update.
#0 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\BaseModel.php(896): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Model.php(718): CodeIgniter\BaseModel->update(Array, Array)
#2 C:\Users\Ace\Desktop\krefa\app\Controllers\PeopleApi.php(67): CodeIgniter\Model->update('2', Array)
#3 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\PeopleApi->update('2')
#4 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PeopleApi))
#5 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\Ace\Desktop\krefa\public\index.php(36): CodeIgniter\CodeIgniter->run()
#7 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\Users\\Ace\\De...')
#8 {main}
CRITICAL - 2021-06-08 19:08:23 --> There is no data to update.
#0 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\BaseModel.php(896): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Model.php(718): CodeIgniter\BaseModel->update(Array, Array)
#2 C:\Users\Ace\Desktop\krefa\app\Controllers\PeopleApi.php(67): CodeIgniter\Model->update('2', Array)
#3 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\PeopleApi->update('2')
#4 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PeopleApi))
#5 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\Users\Ace\Desktop\krefa\public\index.php(36): CodeIgniter\CodeIgniter->run()
#7 C:\Users\Ace\Desktop\krefa\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\Users\\Ace\\De...')
#8 {main}
